# ============================================================
# IDS — Politique de Sécurité
# Format : username;resource;task;start_date;end_date;active
# Dates  : YYYY-MM-DD
# Active : 1=oui, 0=non
# Tâches : read, write, delete, execute, admin, login,
#          failed_login, backup, restore, connect
# ============================================================
alice;database;read;2026-01-01;2026-12-31;1
alice;database;write;2026-01-01;2026-12-31;1
alice;database;admin;2026-01-01;2026-12-31;1
alice;ssh_server;login;2026-01-01;2026-12-31;1
alice;system;execute;2026-01-01;2026-12-31;1
bob;database;read;2026-01-01;2026-06-30;1
bob;web_server;read;2026-01-01;2026-12-31;1
bob;web_server;write;2026-01-01;2026-12-31;1
bob;ssh_server;login;2026-01-01;2026-12-31;1
charlie;file_storage;read;2026-01-01;2026-12-31;1
charlie;file_storage;write;2026-03-01;2026-09-30;1
charlie;ssh_server;login;2026-01-01;2026-12-31;1
